In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


import sys
S=range(1000)
print("Size of each element of list in bytes: ",sys.getsizeof(S))


In [ ]:
import sys
S= range(1000)
print("Size of each element of list in bytes: ",sys.getsizeof(S))

Size of each element of list in bytes:  48


In [ ]:
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))

Size of the whole list in bytes:  48000


In [ ]:
D=np.arange(1000)
print("Size of each element of the Numpy array in bytes: ",D.itemsize)

Size of each element of the Numpy array in bytes:  4


In [ ]:
print("Size of the whole list in bytes: ",D.size*D.itemsize)

Size of the whole list in bytes:  4000


In [ ]:
arr=np.array(42)
print(arr)

42


In [ ]:
zeros_arr=np.zeros((5,2))
zeros_arr1=np.zeros(5)
print(zeros_arr)
print(zeros_arr1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0.]


In [ ]:
zeros_arr=np.zeros((2,3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print("Data type of the array: ",zeros_arr.dtype)

Data type of the array:  float64


In [ ]:
zeros_arr_int = np.zeros((3,3), dtype=np.int16)
print("\nArray of zeros with integer elements: \n",zeros_arr_int)


Array of zeros with integer elements: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
ones_arr = np.ones(6)
print(ones_arr)
print("\nData type of the array: ",ones_arr.dtype)

[1. 1. 1. 1. 1. 1.]

Data type of the array:  float64


In [ ]:
empty_arr = np.empty((3,2))
print(empty_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
print("\nData type of the array: ",empty_arr.dtype)


Data type of the array:  float64


In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
arr2=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr2)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
arr=np.array(3)
print(arr)

3


In [ ]:
 arr=np.array([1,2,3])
 print(arr.dtype)

int64


In [3]:
import numpy as np
arr=np.array([1,2,3],dtype=np.float64)
print(arr.dtype)

float64


In [5]:
arr=np.arange(2)
print(arr)


[0 1]


In [6]:
arr=np.random.randn(3)
print(arr)

[-0.60978033  0.9397676  -0.66189848]


In [7]:
arr=np.arange(12)
arr1=arr.reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
arr=np.arange(10)
arr1=arr.reshape(2,5)
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
arr=np.arange(12)
arr1=arr.ravel()
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
arr=np.arange(12)
arr1=arr.flatten()
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [14]:
arr=np.arange(12)
arr1=arr.flatten()
arr[1]=50
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
arr=np.arange(12)
print(arr[:7])

[0 1 2 3 4 5 6]


In [16]:
arr=np.arange(34)
print(arr[6:20])

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [17]:
arr=np.arange(23)
print(arr[20:6:-2])

[20 18 16 14 12 10  8]


In [18]:
arr=np.array([[1,2,3,4,5,15,17,18,20],[6,7,8,9,10,11,31,18,21]])
arr1=arr.reshape(3,-1)
print(arr1)

[[ 1  2  3  4  5 15]
 [17 18 20  6  7  8]
 [ 9 10 11 31 18 21]]


In [22]:
arr1=np.array([[1,2,3],[4,12,13]])
arr2=np.array([[6,17,8],[14,5,16]])
g=arr1>arr2
l=arr1<arr2
e=arr1==arr2
print(g)

[[False False False]
 [False  True False]]


In [23]:
print(l)


[[ True  True  True]
 [ True False  True]]


In [25]:
print(e)

[[False False False]
 [False False False]]


In [26]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,-1])

3


In [27]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.equal(arr1,arr2)
print(arr)

[False False False]


In [28]:
arr=np.array([1,2,3,4,5])
arr1=arr.astype('f')
print(arr1)

[1. 2. 3. 4. 5.]


In [29]:
arr1=np.array([1,2,3])
arr2=np.array([4.,5.,6.])
arr=arr1.astype(arr2.dtype)
print(arr)

[1. 2. 3.]


In [34]:
arr=np.arange(12)
arr[2:]=10
print(arr1)

[1 2 3]


In [35]:
arr=np.arange(12)
arr[::3]=50
print(arr)

[50  1  2 50  4  5 50  7  8 50 10 11]


In [36]:
a=np.arange(12)
b=a.reshape(3,4)
c=b>4
print(c)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [37]:
arr=np.arange(12)
print(np.transpose(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
arr=np.arange(12)
arr1=arr.reshape(3,4)
print(arr1.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [43]:
arr=np.arange(12)
arr1=arr.reshape(3,4)
print(arr1,arr1.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [47]:
arr=np.arange(12)
arr1=arr.reshape(3,4)
print(np.swapaxes(arr1,0,1))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
